### ISSUE TITLE
Password protection via HTTP basic auth or custom header

### ISSUE THREAD

**Issue by Nowaker** [italux/sentry-prometheus-exporter#17]
**Describe the solution you'd like**

Show the metrics only when HTTP basic auth is passed, or a token is passed in a custom header, e.g. `X-Token`. 

Enable the feature by passing an environment variable, e.g. `SENTRY_EXPORTER_TOKEN`.

**Describe alternatives you've considered**

Using reverse proxies is an overkill given simple authentication can be easily achieved in a WSGI application. With simple auth built into the application, we can easily deploy the Docker image in Kubernetes without adding an extra nginx just to handle something that can be achieved with a single WSGI middleware.

**Comment by italux** [comment]
@Nowaker [New release generated](https://github.com/italux/sentry-prometheus-exporter/releases/tag/v0.6.0) and [docker image updated](https://hub.docker.com/layers/italux/sentry-prometheus-exporter/v0.6.0/images/sha256-ad1e3ee50b8cc456257211b664be93746c427e108c9a02d960af8c6e092c12c0?context=repo)
